load_generic_config "sim"

# Find run68-sim.sh relative to this board file
set boarddir [file dirname [info script]]
set toolsdir [file normalize "$boarddir/../../tools"]

set_board_info sim "$toolsdir/run68-sim.sh"
set_board_info sim,options ""
set_board_info target_install {m68k-human68k}
set_board_info is_simulator 1
set_board_info gcc,stack_size 262144
set_board_info gcc,no_trampolines 1
set_board_info ldflags "-Wl,--defsym,__stack_size=262144"
